<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.security.request_matcher.4mTgYIV' shared service.

return $this->privates['.security.request_matcher.4mTgYIV'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/oauth/v2/token');
