<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_cms_plugin.menu.content_management' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Menu/ContentManagementMenuBuilder.php';

return $this->privates['bitbag_sylius_cms_plugin.menu.content_management'] = new \BitBag\SyliusCmsPlugin\Menu\ContentManagementMenuBuilder();
