<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'loevgaard_sylius_brand.form.extension.type.product' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/vendor/loevgaard/sylius-brand-plugin/src/Form/Extension/ProductTypeExtension.php';

return $this->privates['loevgaard_sylius_brand.form.extension.type.product'] = new \Loevgaard\SyliusBrandPlugin\Form\Extension\ProductTypeExtension('Loevgaard\\SyliusBrandPlugin\\Entity\\Brand');
