<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'loevgaard_sylius_brand.listener.admin.menu_builder' shared service.

include_once $this->targetDirs[3].'/vendor/loevgaard/sylius-brand-plugin/src/Menu/AdminMenuListener.php';

return $this->privates['loevgaard_sylius_brand.listener.admin.menu_builder'] = new \Loevgaard\SyliusBrandPlugin\Menu\AdminMenuListener();
