<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'loevgaard_sylius_brand.factory.brand' shared service.

return $this->services['loevgaard_sylius_brand.factory.brand'] = new \Sylius\Component\Resource\Factory\Factory('Loevgaard\\SyliusBrandPlugin\\Entity\\Brand');
